if [ -d $ZSH_HOME ]; then
    for file in $ZSH_HOME/*.zsh; do
        source $file
    done
fi

mkdir -p $ZSH_CACHE

share_plugins=(
    /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh             # arch-based
    /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh     # arch-based
    /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh                         # debian-base
    /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh                 # debian-based
)
for file in $share_plugins; do
    if [ -f $file ]; then
        source $file
    fi
done

fpath=(
    /usr/share/zsh/site-functions/zsh-completions
    $fpath
)

## OH-MY-ZSH
export ZSH="$HOME/.oh-my-zsh"                # path to oh-my-zsh installation
plugins=(
    alias-finder
    command-not-found
    extract
    z
    git
)
source $ZSH/oh-my-zsh.sh

post_configure
